import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
// import { getSignedUser } from "@/lib/getSingedUser";
// import { cookies } from "next/headers";
import { UserProvider } from "@/hooks/context/userContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // // Get token from cookies
  // const cookieStore = await cookies();
  // const token = cookieStore.get("token")?.value; // Get token from cookies
  // console.log(token);
  // // Only fetch user data if token is available (i.e., the user is logged in)
  // let user: object | null = null;
  // if (token) {
  //   try {
  //     console.log("Fetching user data...");

  //     user = await getSignedUser(token); // Fetch user data from your API
  //   } catch (error) {
  //     console.error("Error fetching user data:", error);
  //   }
  // }

  // console.log("user in layout", user);

  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          "relative h-full font-sans antialiased",
          geistSans.className
        )}
      >
        <main className="relative flex flex-col min-h-screen">
          <UserProvider>
            <Navbar />
            <div className="flex-grow flex-1"> {children}</div>
          </UserProvider>
        </main>

        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
